name: camera_worker
description: A library that converts streaming images from a camera to luminance information for easy processing, and supports parallel processing by Isolate.
version: 1.0.0
homepage: https://github.com/zuvola/camera_worker

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.9.4+18
  flutter:
    sdk: flutter
  isoworker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
